# fly.toml app configuration file generated for server-little-cherry-7613 on 2025-06-08T15:07:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-little-cherry-7613'
primary_region = 'iad'

[env]
  PORT = "9208"
  NODE_ENV = "production"

[build]

[http_service]
  internal_port = 9208
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Health check for HTTP service
  [http_service.http_check]
    interval = '30s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
