# fly.toml app configuration file for Geckos.io multiplayer server
# Optimized for UDP/WebRTC support and production deployment

app = "server-empty-night-5383"
primary_region = "iad"

[build]
  # Install Node.js dependencies during build
  [build.args]
    NODE_VERSION = "18"

[env]
  PORT = "9208"
  NODE_ENV = "production"

# Geckos.io TCP service for signaling (port 9208)
[[services]]
  protocol = "tcp"
  internal_port = 9208
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 9208
    handlers = ["http", "tls"]

[machine]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 2

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
