# fly.toml app configuration file for Geckos.io multiplayer server
# Optimized for UDP/WebRTC support and production deployment

app = "server-empty-night-5383"
primary_region = "iad"

[build]
  [build.args]
    NODE_VERSION = "18"

[env]
  PORT = "9208" # Your app's internal TCP port
  NODE_ENV = "production"

# This service handles the TCP signaling via the standard HTTP/S ports.
# Clients connect to port 443, and Fly forwards it to internal_port 9208.
[[services]]
  protocol = "tcp"
  internal_port = 9208
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# This service handles the UDP traffic for WebRTC data channels.
# Opens multiple UDP ports for WebRTC connections
[[services]]
  protocol = "udp"
  internal_port = 9208 # All UDP traffic also goes to your app on this port
  
  [[services.ports]]
    port = 10000
  [[services.ports]]
    port = 10001
  [[services.ports]]
    port = 10002
  [[services.ports]]
    port = 10003
  [[services.ports]]
    port = 10004
  [[services.ports]]
    port = 10005
  [[services.ports]]
    port = 10006
  [[services.ports]]
    port = 10007
  [[services.ports]]
    port = 10008
  [[services.ports]]
    port = 10009

# Machine configuration
[machine]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 2

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
