// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Matthew Kissinger
/**
 * Newsheepdogland coastline polygon. Cycle 64 (renamed from Wolf Coast in
 * Cycle 66).
 *
 * The single prebaked artifact for the boot-shaped island. This SAME array
 * drives three things so the rendered coast can never drift from the sim
 * boundary:
 *   1. shared/scenes/newsheepdogland.js - the `coastline` boundary the sim steers on,
 *   2. scripts/bake-heightmap.mjs (--boundary coastline --points) - masks the
 *      terrain to sea outside the polygon,
 *   3. shared/CoastlineField.js - both client and Worker build an identical SDF
 *      from it at load.
 *
 * Generated by tools/author-newsheepdogland.mjs (provenance): a boot traced
 * counter-clockwise, densified into banking curves, uniformly scaled to a
 * 3.200 km^2 silhouette and recentred on the origin. +X east (toe), +Z north
 * (mountain / leg top). 75 vertices. bbox x[-1174, 1174], z[-1494, 1494].
 *
 * Pure data: no imports, no DOM, deterministic. Safe for shared/.
 */

/** @type {Array<{x: number, z: number}>} */
export const NEWSHEEPDOGLAND_POINTS = [
    { x: -936, z: 1459 }, { x: -968, z: 1314 }, { x: -1000, z: 1168 }, { x: -988, z: 1023 },
    { x: -977, z: 878 }, { x: -997, z: 732 }, { x: -1017, z: 587 }, { x: -1000, z: 442 },
    { x: -982, z: 296 }, { x: -1003, z: 151 }, { x: -1023, z: 6 }, { x: -1011, z: -140 },
    { x: -1000, z: -285 }, { x: -1006, z: -401 }, { x: -1011, z: -517 }, { x: -1052, z: -634 },
    { x: -1093, z: -750 }, { x: -1134, z: -866 }, { x: -1174, z: -982 }, { x: -1151, z: -1099 },
    { x: -1128, z: -1215 }, { x: -1052, z: -1302 }, { x: -977, z: -1389 },
    { x: -825, z: -1430 }, { x: -674, z: -1471 }, { x: -558, z: -1478 }, { x: -442, z: -1486 },
    { x: -326, z: -1494 }, { x: -200, z: -1492 }, { x: -74, z: -1490 }, { x: 52, z: -1488 },
    { x: 178, z: -1478 }, { x: 304, z: -1469 }, { x: 430, z: -1459 }, { x: 590, z: -1430 },
    { x: 750, z: -1401 }, { x: 866, z: -1349 }, { x: 982, z: -1296 }, { x: 1061, z: -1215 },
    { x: 1139, z: -1134 }, { x: 1157, z: -1046 }, { x: 1174, z: -959 }, { x: 1081, z: -820 },
    { x: 974, z: -808 }, { x: 866, z: -796 }, { x: 721, z: -814 }, { x: 575, z: -831 },
    { x: 430, z: -843 }, { x: 285, z: -855 }, { x: 148, z: -857 }, { x: 12, z: -860 },
    { x: -81, z: -762 }, { x: -174, z: -663 }, { x: -198, z: -503 }, { x: -221, z: -343 },
    { x: -213, z: -227 }, { x: -205, z: -110 }, { x: -198, z: 6 }, { x: -203, z: 122 },
    { x: -209, z: 238 }, { x: -215, z: 355 }, { x: -207, z: 471 }, { x: -200, z: 587 },
    { x: -192, z: 703 }, { x: -200, z: 820 }, { x: -207, z: 936 }, { x: -215, z: 1052 },
    { x: -221, z: 1168 }, { x: -227, z: 1285 }, { x: -233, z: 1401 }, { x: -351, z: 1432 },
    { x: -469, z: 1463 }, { x: -587, z: 1494 }, { x: -703, z: 1482 }, { x: -820, z: 1471 },
];
