// Generated by Wrangler by running `wrangler types`

interface Env {
	ROOM_DO: DurableObjectNamespace<import("./src/index").RoomDO>;
	LOBBY_DO: DurableObjectNamespace<import("./src/index").LobbyDO>;
	DB: D1Database;
}
